# The method computes the differeces between a set of 
# JOREK generated images and a reference image which
# is generated by the JOREK synthetic camera

# norm 2 function
def norm_2(data):
  from numpy import sum as npsum
  from numpy import sqrt
  return sqrt(npsum(data*data))

# norm 1 function
def norm_1(data):
  from numpy import sum as npsum
  from numpy import abs as npabs
  return npsum(npabs(data))

# norm infinite function
def norm_inf(data):
  from numpy import abs as npabs
  from numpy import amax
  return amax(npabs(data))

# compute convergence rate
def compute_convergence_rate(x,y):
  from scipy.stats import linregress
  from numpy import log
  slope,intercept,rvalue,pvalue,stderr = \
  linregress(log(x),y=log(y),alternative='two-sided')
  return slope

# read and store only one dataset
def read_datasets_from_hdf5(filename,filepath,separator):
  from h5py import File
  from numpy import array,transpose
  path = "".join([filepath,separator,filename])
  print('Reading file: ',path)
  fhandler = File(path)
  pixel_filter_intensity = transpose(array(fhandler['pixel_filter_intensities']),[3,4,0,1,2])
  pixel_intensity  = pixel_filter_intensity[0]
  filter_intensity = pixel_filter_intensity[1]
  x_position = array(fhandler['x_pixel_coordinates'])
  y_position = array(fhandler['y_pixel_coordinates'])
  fhandler.close()
  return pixel_intensity,filter_intensity,x_position,y_position

# read and store the JOREK datasets
def read_datasets_from_multiple_hdf5(filenames,filepath,separator):
  from h5py import File
  from numpy import array,transpose
  pixel_intensities = []
  filter_intensities = []
  x_positions       = []
  y_positions       = []
  for filename in filenames:
    pixel_intensity,filter_intensity,x_position,y_position = \
    read_datasets_from_hdf5(filename,filepath,separator)
    pixel_intensities.append(pixel_intensity)
    filter_intensities.append(filter_intensity)
    x_positions.append(x_position); y_positions.append(y_position);
  return pixel_intensities,filter_intensities,x_positions,y_positions

# Method used for plotting 4d arrays as 2d image
def imshow_3d(fig,ax,frame,x_positions=[],y_positions=[],title="",fontsize=12):
  from numpy import newaxis
  from matplotlib.pyplot import figure,imshow,colorbar
  from matplotlib.pyplot import title as tit
  # plot with extension
  for timeid,timeframe in enumerate(frame):
    if(not ((len(x_positions)==0) and (len(y_positions)==0))):
      dx = 0.5*(x_positions[timeid,1]-x_positions[timeid,0])
      dy = 0.5*(y_positions[timeid,1]-y_positions[timeid,0])
      ext = [x_positions[timeid,0]-dx, x_positions[timeid,-1]+dx,\
      y_positions[timeid,0]-dy,y_positions[timeid,-1]+dy]
    else:
      ext = None
    for spectrum_id,spectrum in enumerate(timeframe):
      im=ax.imshow(spectrum,extent=ext)
      fig.colorbar(im,ax=ax)
      ax.set_title("".join([title," time N# ",str(timeid+1),\
      ' spectrum N# ',str(spectrum_id+1)]),fontsize=fontsize)

# do 2d convergence plot
def plot_convergence_2d(fig,ax,x,values,title='',fontsize=12,xlabel='x',ylabel='error',\
loglog=True,linewidth=3,markersize=10,markertype='s'):
  from numpy import round as npround
  if(loglog):
    for spectrumid,spectrum in enumerate(values):
      ax.loglog(x,spectrum,linewidth=linewidth,markersize=markersize,\
      marker=markertype,label="".join(["spectrum N#: ",str(spectrumid),\
      ' conv. rate: ',str(npround(compute_convergence_rate(x,spectrum),decimals=3))]))
  else:
    for spectrumid,spectrum in enumerate(values):
      ax.plot(x,spectrum,linewidth=linewidth,markersize=markersize,\
      marker=markertype,label="".join(["spectrum N#: ",str(spectrumid),\
      ' conv. rate: ',str(npround(compute_convergence_rate(x,spectrum),decimals=3))]))
  ax.set_title(title,fontsize=fontsize)
  ax.set_xlabel(xlabel,fontsize=fontsize)
  ax.set_ylabel(ylabel,fontsize=fontsize)
  ax.tick_params(axis='x',labelsize=fontsize)
  ax.tick_params(axis='y',labelsize=fontsize)
  ax.legend()
  ax.grid()

# compute the differences and error between a set of images and a reference image
def compute_difference_between_images(test_images,reference_image):
  from numpy import amax
  from numpy import abs as npabs
  image_difference = []; normalised_image_difference = [];
  for test_image in test_images:
    image_difference.append(test_image-reference_image) 
  # compute the normalised difference
  normalised_reference_image = reference_image/amax(npabs(reference_image))
  for test_image in test_images:
    normalised_image_difference.append((test_image/amax(npabs(test_image)))-\
    normalised_reference_image)
  return image_difference,normalised_image_difference

# compute the integrated errors for both pixel and filter intensities
def compute_integrate_error(image_differences,\
norm_dict={'norm_1':norm_1,'norm_2':norm_2,'norm_inf':norm_inf}):
  from numpy import array,transpose
  error_norm = {}
  for normkey,norm in norm_dict.items():
    error = []
    for frame in image_differences:
      spectral_error = []
      for spectrum in frame:
        spectral_error.append(norm(spectrum))
      error.append(spectral_error)
    error_norm[normkey] = transpose(array(error),[1,0])
  return error_norm

# compute the differences between images and a reference image and the 
# error using different norms
def compute_difference_error_pixel_filter_intensities(x,test_images,reference_image,\
test_x_positions=[],test_y_positions=[],\
norm_dict={'norm_1':norm_1,'norm_2':norm_2,'norm_inf':norm_inf},fontsize=12,xlabel='x',\
loglog=True,linewidth=3,markersize=10,markertype='s',title='image'):
  from matplotlib.pyplot import figure,show
  # compute image differences and norm errors
  image_differences,normalised_image_differences = compute_difference_between_images(\
  test_images,reference_image)
  norm_errors = compute_integrate_error(image_differences,norm_dict=norm_dict)
  # plot image differences
  figs = []; axs = [];
  for image_diff_id,image_diff in enumerate(image_differences):
    figs.append(figure(image_diff_id+1,facecolor='white',edgecolor='white'))
    axs.append([figs[image_diff_id].add_subplot(111)])
    imshow_3d(figs[image_diff_id],axs[image_diff_id][0],image_diff,\
    x_positions=test_x_positions[image_diff_id],y_positions=test_y_positions[image_diff_id],\
    title="".join(["Differences test ",title," N#: ",str(image_diff_id)]),fontsize=fontsize)
  show()
  # plot normalised image defferences
  figs = []; axs = [];
  for image_diff_id,image_diff in enumerate(normalised_image_differences):
    figs.append(figure(image_diff_id+1,facecolor='white',edgecolor='white'))
    axs.append([figs[image_diff_id].add_subplot(111)])
    imshow_3d(figs[image_diff_id],axs[image_diff_id][0],image_diff,\
    x_positions=test_x_positions[image_diff_id],y_positions=test_y_positions[image_diff_id],\
    title="".join(["Normalised differences test ",title," N#: ",str(image_diff_id)]),fontsize=fontsize)
  show()
  # plot the error w.r.t.a set of norms
  figs = []; axs = [];
  for keyid,errorkey in enumerate(norm_errors.keys()):
    figs.append(figure(keyid+1,facecolor='white',edgecolor='white'))
    axs.append([figs[keyid].add_subplot(111)])
    plot_convergence_2d(figs[keyid],axs[keyid][0],x,norm_errors[errorkey],\
    title="".join([title," error using norm: ",errorkey]),fontsize=fontsize,\
    xlabel=xlabel,ylabel="".join(["Error norm: $",errorkey,"$"]),loglog=loglog,\
    linewidth=linewidth,markersize=markersize,markertype=markertype)
  show()

# main wrapper
def read_and_plot_image_differences_errors(x,test_filenames,reference_filename,\
separator,filepath,norm_dict={'norm_1':norm_1,'norm_2':norm_2,'norm_inf':norm_inf},\
fontsize=12,xlabel='x',loglog=True,linewidth=3,markersize=10,markertype='s'):
  # read test and reference data
  test_pixel_intensities,test_filter_intensities,test_x_positions,test_y_positions = \
  read_datasets_from_multiple_hdf5(test_filenames,filepath,separator)
  ref_pixel_intensity,ref_filter_intensity,ref_x_position,ref_y_positions = \
  read_datasets_from_hdf5(reference_filename,filepath,separator)
  # compute and plot the pixel intensity error
  compute_difference_error_pixel_filter_intensities(x,test_pixel_intensities,\
  ref_pixel_intensity,test_x_positions=test_x_positions,\
  test_y_positions=test_y_positions,norm_dict=norm_dict,fontsize=fontsize,\
  xlabel=xlabel,loglog=loglog,linewidth=linewidth,markersize=markersize,\
  markertype=markertype,title='image')
  # compute and plot the filter intensity error
  compute_difference_error_pixel_filter_intensities(x,test_filter_intensities,\
  ref_filter_intensity,test_x_positions=test_x_positions,\
  test_y_positions=test_y_positions,norm_dict=norm_dict,fontsize=fontsize,\
  xlabel=xlabel,loglog=loglog,linewidth=linewidth,markersize=markersize,\
  markertype=markertype,title='filter')

# generate function pointer dictionaries from string list
def generate_function_pointers_from_names(names):
  import __main__
  pointer_dict = {}
  for name in names:
    try:
      pointer_dict[name] = getattr(__main__,name)
    except:
      print("WARNING function ",name," not defined: skip!")
  return pointer_dict

# argument parser
def generate_argument_parser():
  from numpy import float64
  import argparse
  parser = argparse.ArgumentParser(description='plot differences and errors between images')
  parser.add_argument('--conv_values','-cval',type=float64,nargs='*',required=True,action='store',\
  dest='x',help='list of values used for convergence study')
  parser.add_argument('--test_image_filenames','-tf',type=str,nargs='*',required=True,action='store',\
  dest='test_filenames',help='name of the files containing the test pixel/filter intensities')
  parser.add_argument('--reference_image_filename','-rf',type=str,required=False,\
  dest='ref_filename',action='store',default='.',help='name of the file containing the test pixel/filter intensity')
  parser.add_argument('--filepath','-fp',type=str,required=False,\
  dest='filepath',action='store',default='.',help='path to the hdf5 to be loaded, default: .')
  parser.add_argument('--separator','-sep',type=str,required=False,\
  dest='separator',action='store',default='/',help='file separator, default: /')
  parser.add_argument('--fontsize','-fsize',type=int,required=False,\
  dest='fontsize',action='store',default=12,help='fontsize for videos, default: 12')
  parser.add_argument('--markersize','-msize',type=int,required=False,\
  dest='markersize',action='store',default=10,help='marker size, default: 10')
  parser.add_argument('--markertype','-mtype',type=str,required=False,\
  dest='markertype',action='store',default='s',help='marker type, default: s (square)')
  parser.add_argument('--linewidth','-lw',type=int,required=False,\
  dest='linewidth',action='store',default=3,help='line width, default: 3')
  parser.add_argument('--xlabel','-xlab',type=str,required=False,dest='xlabel',action='store',\
  default='N# particles',help='name of the convergence parameter, default: N# particles')
  parser.add_argument('--loglog_plot','-logp',type=bool,required=False,\
  dest='loglog',action='store',default=True,help='plot convergence using logarithm plot, default: True')
  parser.add_argument('--norms_names','-nm',type=str,nargs='*',required=False,\
  dest='norm_names',action='store',default=['norm_1','norm_2','norm_inf'],\
  help='names of the norms to be used, default: norms_1, norms_2, norm_inf')
  return parser.parse_args()

if __name__ == '__main__':
  args = generate_argument_parser()
  norms_dict = generate_function_pointers_from_names(args.norm_names)
  read_and_plot_image_differences_errors(args.x,args.test_filenames,args.ref_filename,\
  args.separator,args.filepath,norm_dict=norms_dict,fontsize=args.fontsize,\
  xlabel=args.xlabel,loglog=args.loglog,linewidth=args.linewidth,\
  markersize=args.markersize,markertype=args.markertype)
 
