# ----------------------------------------------- #
# Plot SOFT pdf generated by JOREK                #
# ----------------------------------------------- #

# load data
def load_pdf_data(filename,filepath=".",separator="/"):
  from h5py import File
  from numpy import array
  fhandler = File("".join([filepath,separator,filename]),'r')
  minor_radii = array(fhandler['r'])
  xi_mesh_list = []; p_mesh_list = []; pdf = [];
  for radius_id in range(len(minor_radii)):
    pdf_dict = fhandler[''.join(['r',str(radius_id)])]
    xi_mesh_list.append(array(pdf_dict['xi']))
    p_mesh_list.append(array(pdf_dict['p']))
    pdf.append(array(pdf_dict['f']))
  fhandler.close()
  return pdf,p_mesh_list,xi_mesh_list,minor_radii

# method used for inegrating the pdf assuming the mesh to be uniform
def integrate_2d_pdf(pdf_list,xi_mesh_list,p_mesh_list,minor_radii):
  from numpy import array,power,matmul
  from numpy import sum as npsum
  rho_r = []
  for pdf_id,pdf in enumerate(pdf_list):
    p_mesh = p_mesh_list[pdf_id]; dp = p_mesh[1]-p_mesh[0];
    dxi = xi_mesh_list[pdf_id][1] - xi_mesh_list[pdf_id][0];
    rho_r.append(npsum(matmul(power(p_mesh,2),pdf))*dp*dxi)
  return [array(rho_r)],[minor_radii]

# plot 1d features
def plot1d(fig,ax,x,y,fontsize=12,linewidth=3,markertype='s',\
markersize=12,xlabel='x',ylabel='y',title=''):
  ax.plot(x,y,linewidth=linewidth,marker=markertype,markersize=markersize)
  ax.set_title(title,fontsize=fontsize)
  ax.set_xlabel(xlabel,fontsize=fontsize); ax.set_ylabel(ylabel,fontsize=fontsize);
  ax.tick_params(axis='x',labelsize=fontsize)
  ax.tick_params(axis='y',labelsize=fontsize)
  ax.grid()

# compute and plot 1d pdf
def compute_plot_1d_pdf(pdf_list,xi_mesh_list,p_mesh_list,minor_radii,\
xlabels,ylabels,titles,fontsize=12,linewidth=3,markertype='s',markersize=12):
  from matplotlib.pyplot import figure,show
  # initialisation
  figs = []; axs = [];
  # compute the 1d pdf
  pdf_1d_list,mesh_1d_list = integrate_2d_pdf(pdf_list,xi_mesh_list,p_mesh_list,minor_radii)
  # do plots
  for pdf_1d_id,pdf_1d in enumerate(pdf_1d_list):
    figs.append(figure(pdf_1d_id+1,facecolor='white',edgecolor='white'))
    axs.append([figs[pdf_1d_id].add_subplot(111)])
    plot1d(figs[pdf_1d_id],axs[pdf_1d_id][0],mesh_1d_list[pdf_1d_id],\
    pdf_1d_list[pdf_1d_id],xlabel=xlabels[pdf_1d_id],\
    ylabel=ylabels[pdf_1d_id],title=titles[pdf_1d_id],fontsize=fontsize,\
    linewidth=linewidth,markertype=markertype,markersize=markersize)
  show()

# wrapper function of
def compute_and_plot_soft_pdf(filename,titles_1d,xlabels_1d,ylabels_1d,\
filepath=".",separator="/",fontsize=12,linewidth=3,\
markertype='s',markersize=12):
  # read soft pdf
  pdf_list,p_mesh_list,xi_mesh_list,minor_radii = load_pdf_data(\
  filename,filepath=filepath,separator=separator)
  # do 1d plot
  compute_plot_1d_pdf(pdf_list,xi_mesh_list,p_mesh_list,minor_radii,\
  xlabels_1d,ylabels_1d,titles_1d,fontsize=fontsize,linewidth=linewidth,\
  markertype=markertype,markersize=markersize)

# Argument parser ------------------------------- #
def generate_argument_parser():
  import argparse
  parser = argparse.ArgumentParser(\
  description='read and plot SOFT compatible PDF from JOREK')
  parser.add_argument('--filename','-f',type=str,action='store',\
  required=True,help='SOFT PDF file to be read')
  parser.add_argument('--filepath','-fp',type=str,required=False,\
  dest='filepath',action='store',default='.',\
  help='path to light and camera hdf5 files to be loaded, default: .')
  parser.add_argument('--separator','-sep',type=str,required=False,\
  dest='separator',action='store',default='/',help='file separator, default: /')
  parser.add_argument('--titles_pdf_1d','-titpdf1d',type=str,nargs='*',required=False,\
  dest='titles_1d',action='store',default=["Integrated SOFT pdf vs minor radius"],\
  help='titles of the 1d distribution functions')
  parser.add_argument('--xlabels_1d','-xlab1d',type=str,nargs='*',required=False,\
  dest='xlabels_1d',action='store',default=["r [m]"],\
  help='x labels of the 1d distribution functions')
  parser.add_argument('--ylabels_1d','-ylab1d',type=str,nargs='*',required=False,\
  dest='ylabels_1d',action='store',default=["pdf [m-1]"],\
  help='y labels of the 1d distribution functions')
  parser.add_argument('--fontsize','-font',type=int,required=False,\
  dest='fontsize',action='store',default=16,help='plot font size, default: 16')
  parser.add_argument('--markersize','-ms',type=int,required=False,\
  dest='markersize',action='store',default=12,help='marker size, default: 12')
  parser.add_argument('--linewidth','-lw',type=int,required=False,\
  dest='linewidth',action='store',default=3,help='line width, default: 12')
  parser.add_argument('--markertype','-mt',type=str,required=False,\
  dest='markertype',action='store',default='s',help='marker type, default: s')
  return parser.parse_args()

# Main function --------------------------------- #
if __name__ == "__main__":
  args = generate_argument_parser()
  compute_and_plot_soft_pdf(args.filename,args.titles_1d,args.xlabels_1d,\
  args.ylabels_1d,separator=args.separator,filepath=args.filepath,\
  fontsize=args.fontsize,linewidth=args.linewidth,\
  markertype=args.markertype,markersize=args.markersize)

# ----------------------------------------------- #
